services:
  - type: web
    name: learnova-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
